export const DEFAULT_HEDGING_PHRASES: string[] = [
  'I think',
  'I believe',
  'I assume',
  'I suppose',
  'I guess',
  'it seems',
  'it appears',
  'it looks like',
  'it might be',
  'possibly',
  'probably',
  'perhaps',
  'maybe',
  'likely',
  'not sure',
  "I'm not certain",
  "I'm not sure",
  'could be',
  'might be',
  'may be',
  'as far as I know',
  'to the best of my knowledge',
];

export const DEFAULT_REFUSAL_PHRASES: string[] = [
  "I can't",
  'I cannot',
  "I'm unable to",
  'I am unable to',
  "I won't",
  'I will not',
  "I'm not able to",
  "I'm sorry, but",
  'I apologize, but',
  "I don't feel comfortable",
  'That is not something I can',
  'As an AI',
  'As a language model',
];

export const DEFAULT_SYSTEM_PROMPT_PATTERNS: RegExp[] = [
  /you are a|your name is|your role is|your job is/i,
  /system prompt|system message|system instruction/i,
  /ignore (all )?(previous|prior) instruction/i,
  /you must|you should always|never (say|tell|reveal)/i,
];
